title: YuK0t
email: info@yu-kot.com
description: "Юрій (@YuK0t): блог про ШІ, no-code, автоматизацію та дизайн. Чат-боти, сайти, автоматизація від $10/год."
baseurl: ""
url: "https://yu-kot.github.io"
remote_theme: pmarsceill/just-the-docs@v0.8.2
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
languages: ["uk", "en"]
color_scheme: auto
search_enabled: true
footer_content: "© 2025 YuK0t. All rights reserved."
